# docker-compose.yml
version: '3'
services:
  cgt_mail:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - SENDER_EMAIL=musulmete129@gmail.com
      - SENDER_PASSWORD=icpm zsxk pqwm pmjo
      - RECEIVER_EMAIL=musulmete6@gmail.com
      - inMessage=hello cgt software
      - Smtp_Port=587S
      - smtp_server=smtp.gmail.com
  cgt_mail2:
    build:
      context: .
      dockerfile: Dockerfile2
    depends_on:
      - redis
    environment:
      - SENDER_EMAIL=musulmete129@gmail.com
      - SENDER_PASSWORD=icpm zsxk pqwm pmjo
      - RECEIVER_EMAIL=musulmete6@gmail.com
      - inMessage=hello cgt software
      - Smtp_Port=587
      - smtp_server=smtp.gmail.com
  
  redis:
    image: 'redis:latest'  
    ports:
        - "6379:6379"
        - "8001:8001" 

      
